name: ns-sync-upstream

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *' # daily at 3am

permissions:
  contents: write

jobs:
  sync:
    name: sync
    runs-on: nscloud
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0

      - name: git config
        run: |
          git config --global user.name github-actions
          git config --global user.email noreply+github-actions@namespacelabs.com

      - name: fetch upstream
        run: |
          git remote add upstream https://github.com/temporalio/features.git
          git fetch upstream main
          git checkout -t origin/upstream
          git rebase upstream/main

      - name: rebase patches
        run: |
          # Branch patches contains updates that should cleanly rebase.
          # For instance it contains this workflow.

          git checkout -t origin/patches
          git rebase upstream

      - name: sync master
        run: |
          git checkout master
          git reset --hard patches
    

      - name: update workflows
        run: |
          # Remove tests that do not work in forks
          sed -n '/Test with Cloud/q;p' .github/workflows/docker-images.yaml > .github/workflows/docker-images-tmp.yaml
          mv .github/workflows/docker-images-tmp.yaml .github/workflows/docker-images.yaml

          # Update them to run on nscloud.
          sed -e 's/^\([[:space:]]*\)runs-on: .*/\1runs-on: nscloud/' -i .github/workflows/*.y*ml

          git add .
          git commit -m "Update workflows to run on nscloud."

      - name: push
        run: |
           # Push separately to trigger workflows on main.
           git push -f origin upstream
           git push -f origin patches
           git push -f origin main